on:
  push:
    branches: [gui_builder_action]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: ['windows-latest', 'ubuntu-latest, 'macos-latest']
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
        path: src

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller -F --windowed mantavision_gui.py
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
